# Generated by Django 3.2.8 on 2021-10-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0015_alter_dvdbenchtrainingdata_createdat'),
    ]

    operations = [
        migrations.CreateModel(
            name='DVDBenchTestingData',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('CPUUtilization_Average', models.IntegerField()),
                ('NetworkIn_Average', models.IntegerField()),
                ('NetworkOut_Average', models.IntegerField()),
                ('MemoryUtilization_Average', models.DecimalField(decimal_places=10, max_digits=19)),
                ('Final_Target', models.DecimalField(decimal_places=10, max_digits=19)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NDBenchTestingData',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('CPUUtilization_Average', models.IntegerField()),
                ('NetworkIn_Average', models.IntegerField()),
                ('NetworkOut_Average', models.IntegerField()),
                ('MemoryUtilization_Average', models.DecimalField(decimal_places=10, max_digits=19)),
                ('Final_Target', models.DecimalField(decimal_places=10, max_digits=19)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NDBenchTrainingData',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('CPUUtilization_Average', models.IntegerField()),
                ('NetworkIn_Average', models.IntegerField()),
                ('NetworkOut_Average', models.IntegerField()),
                ('MemoryUtilization_Average', models.DecimalField(decimal_places=10, max_digits=19)),
                ('Final_Target', models.DecimalField(decimal_places=10, max_digits=19)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
